source('output/additional_analyses_2026-09-02/code/common.R')
rd<-function(n)fread(file.path(OUT,'tables',paste0(n,'.csv')))
program_names<-c(NETosis='NET-associated genes',Degranulation='Granule / degranulation genes',Oxidative_burst='Oxidative burst',Phagocytosis='Phagocytosis',Chemotaxis='Chemotaxis',OSM_inflammation='OSM / inflammatory genes',Type_I_interferon='Type I interferon',Immature_granulopoiesis='Immature granulopoiesis',Survival_antiapoptosis='Survival / apoptosis genes',Hypoxia_glycolysis='Hypoxia / glycolysis',ER_stress='ER stress',Proliferation_stress='Proliferation / stress',Integrin_adhesion='Integrin / adhesion',CXCR4_aging_retention='CXCR4 / retention')
plab<-function(x)factor(unname(program_names[as.character(x)]),levels=rev(unname(program_names)))
headline<-function(p,title,subtitle,caption='')p+plot_annotation(title=title,subtitle=subtitle,caption=caption,tag_levels='A',theme=theme(plot.title=element_text(family='Arial',size=17,face='bold',color='#15354D'),plot.subtitle=element_text(family='Arial',size=10,color='#4C5665'),plot.caption=element_text(family='Arial',size=8.3,color='#4C5665',hjust=0),plot.margin=margin(12,14,12,14)))
pd<-position_dodge(width=.65)

# Figure 1: show the original estimates and all fixed sensitivity thresholds.
cnt<-rd('canonical_cell_counts')[ConditionCode%in%c('N','NA5','UF','UA5')]
cnt[,condition:=factor(ConditionCode,levels=c('N','NA5','UF','UA5'),labels=c('Alone','Alone + block','UC fibroblasts','UC + block'))]
p1a<-ggplot(cnt,aes(condition,DonorID,fill=log10(cells)))+geom_tile(color='white',linewidth=1)+geom_text(aes(label=cells,color=cells<20),size=3.7,fontface='bold')+scale_fill_gradient(low='#EDF3F8',high='#206A96',guide='none')+scale_color_manual(values=c('FALSE'='#172F42','TRUE'='#C63D35'),guide='none')+labs(title='Recovered canonical neutrophils',subtitle='Red counts identify arms with fewer than 20 cells',x=NULL,y=NULL)+theme_pub+theme(axis.text.x=element_text(angle=15,hjust=1))
co<-rd('composition_donor_contrasts')[contrast=='alpha_interaction'];co[,state_short:=factor(short_state[state],levels=rev(unname(short_state)))];co[,analysis:=factor(min_cells,levels=c(0,20,50),labels=c('All recorded donors (n=6)','At least 20 cells/arm (n=4)','At least 50 cells/arm (n=3)'))]
p1b<-ggplot(co,aes(effect,state_short,color=analysis))+geom_vline(xintercept=0,color='#A4AEB6',linetype=2)+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.15,position=pd)+geom_point(position=pd,size=2.7)+scale_color_manual(values=c('#303C49','#277E9C','#CE7C36'))+labs(title='Context interaction and uncertainty',subtitle='Mean donor difference-in-differences; 95% t intervals',x='Relative abundance interaction (CLR units)',y=NULL,color=NULL)+theme_pub+theme(legend.text=element_text(size=7.5))
dd<-rd('composition_individual_differences')[min_cells==0 & contrast%in%c('alpha_alone','alpha_in_UC')]
dd[,context:=factor(contrast,levels=c('alpha_alone','alpha_in_UC'),labels=c('Alone','With UC fibroblasts'))];dd[,state_short:=factor(short_state[state],levels=unname(short_state))];dd[,sparse_donor:=DonorID%in%c('Donor5','Donor6')]
p1c<-ggplot(dd,aes(context,delta,group=DonorID,color=DonorID,linetype=sparse_donor))+geom_hline(yintercept=0,linetype=2,color='#BDC5CC')+geom_line(linewidth=.6,alpha=.85)+geom_point(size=2)+facet_wrap(~state_short,nrow=1)+scale_linetype_manual(values=c('FALSE'='solid','TRUE'='dashed'),guide='none')+guides(color='none')+labs(title='Blockade effects within individual donors',subtitle='Dashed lines identify donors with a sparse arm; RNA states remain relative measurements',x=NULL,y='Blockade effect (CLR units)')+theme_pub+theme(axis.text.x=element_text(angle=20,hjust=1),strip.text=element_text(size=9))
fig1<-headline((p1a|p1b)/p1c,'Figure 1 | Fibroblast-context interaction: donor and cell-count sensitivity','Culture conditions use recorded Donor1-Donor6 labels; biological matching awaits confirmation.','CLR = centered log ratio among four canonical states. The six-donor estimates reproduce the original effects.\nUncertainty here comes from between-donor variation in the interaction, rather than a shared condition-level residual variance.')+plot_layout(heights=c(1,1))
save_plot(fig1,'Figure_1_donor_context_interaction',11.5,8.7)

# Figure 2: full-gene analysis and prespecified measurement sensitivities.
pp<-rd('population_program_contrasts');gcov<-rd('program_gene_coverage')
a<-pp[population=='Resolved' & version=='full_gene' & min_cells==20 & contrast%in%c('UC_vs_control_fibroblasts','alpha_alone','alpha_in_UC','alpha_interaction')]
a[,program_label:=plab(program)];a[,ct:=factor(contrast,levels=c('UC_vs_control_fibroblasts','alpha_alone','alpha_in_UC','alpha_interaction'),labels=c('UC vs control\nfibroblasts','Blockade\nalone','Blockade\nin UC culture','Context\ninteraction'))]
p2a<-ggplot(a,aes(ct,program_label,fill=effect))+geom_tile(color='white',linewidth=.5)+geom_text(aes(label=paste0(sprintf('%+.2f',effect),ifelse(q<.05,'*',''))),size=2.8)+scale_fill_gradient2(low='#216A94',mid='white',high='#C25443',midpoint=0)+labs(title='Full-gene population program effects',subtitle='At least 20 canonical cells per arm; 4-5 complete donors',x=NULL,y=NULL,fill='Score\nchange')+theme_pub+theme(legend.position='right',axis.text.x=element_text(size=8),axis.text.y=element_text(size=8.5))
cov<-gcov[,.(full=sum(in_full),reduced=sum(in_reduced),defined=.N),by=program];cov[,program_label:=plab(program)]
p2b<-ggplot(cov,aes(y=program_label))+geom_segment(aes(x=reduced/defined,xend=full/defined,yend=program_label),color='#BCC8D1',linewidth=1)+geom_point(aes(x=reduced/defined,color='Reduced mapping genes'),size=2.5)+geom_point(aes(x=full/defined,color='Full expression genes'),size=2.5)+scale_color_manual(values=c('Reduced mapping genes'='#A8B4BD','Full expression genes'='#287FA0'))+scale_x_continuous(labels=scales::percent,limits=c(0,1.04))+labs(title='Gene coverage restored',subtitle='Same 14 gene sets as the earlier analysis',x='Fraction of defined genes available',y=NULL,color=NULL)+theme_pub+theme(axis.text.y=element_blank(),axis.ticks.y=element_blank(),legend.text=element_text(size=7.5))
sel<-c('CXCR4_aging_retention','Chemotaxis','OSM_inflammation','Degranulation','Immature_granulopoiesis','Integrin_adhesion')
sens<-rbindlist(list(pp[contrast=='alpha_interaction' & min_cells==0 & population=='Resolved' & version=='full_gene'][,analysis:='All recorded donors'],pp[contrast=='alpha_interaction' & min_cells==20 & population=='Resolved' & version=='full_gene'][,analysis:='At least 20 cells/arm'],pp[contrast=='alpha_interaction' & min_cells==20 & population=='All annotated' & version=='full_gene'][,analysis:='Include unresolved'],pp[contrast=='alpha_interaction' & min_cells==20 & population=='Resolved' & version=='identity_markers_removed'][,analysis:='Four identity markers removed']))[program%in%sel]
sens[,program_label:=factor(unname(program_names[program]),levels=rev(unname(program_names[sel])))];sens[,analysis:=factor(analysis,levels=c('All recorded donors','At least 20 cells/arm','Include unresolved','Four identity markers removed'))]
p2c<-ggplot(sens,aes(effect,program_label,color=analysis))+geom_vline(xintercept=0,color='#A4AEB6',linetype=2)+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.1,position=pd)+geom_point(position=pd,size=2)+scale_color_manual(values=c('#6E7881','#247C9A','#C48338','#9470AB'))+labs(title='Interaction sensitivity for selected biological programs',subtitle='All 14 programs and all thresholds are supplied in source tables',x='Context interaction (fixed-reference gene z-score units)',y=NULL,color=NULL)+theme_pub+theme(legend.text=element_text(size=8))
fig2<-headline((p2a|p2b)/p2c,'Figure 2 | Full-gene inflammatory programs and contextual drug response','Full RNA counts: 37,302 genes; the earlier mapping carrier contained 3,427 genes.','* BH q < 0.05 across 14 programs within each contrast, using donor-level t tests. Exact sign-flip results are supplied separately.\nThe unresolved-cell sensitivity retains original lineage QC; identified contaminants remain excluded.\nScores summarize transcription, not measured release, antimicrobial function, NET formation, or survival.')+plot_layout(heights=c(1.6,1),widths=c(1.65,1))
save_plot(fig2,'Figure_2_full_gene_programs',11.5,11)

# Figure 3: exact additive decomposition on common state support.
dec<-rd('composition_activity_decomposition_by_donor');dst<-rd('composition_activity_decomposition_statistics')
main<-dst[version=='full_gene' & min_state_cells==10];main[,program_label:=plab(program)];main[,component:=factor(component,levels=c('total','composition','activity'),labels=c('Total change','State composition','Within-state activity'))]
p3a<-ggplot(main,aes(effect,program_label,color=component))+geom_vline(xintercept=0,linetype=2,color='#ABB5BF')+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.1,position=pd)+geom_point(position=pd,size=2)+scale_color_manual(values=c('#293F51','#C1843F','#2C8F86'))+labs(title='Change in UC coculture after blockade',subtitle='Five donors; symmetric decomposition and 95% t intervals',x='Fixed-reference score change',y=NULL,color=NULL)+theme_pub+theme(axis.text.y=element_text(size=8.5),legend.text=element_text(size=8))
mass<-unique(dec[version=='full_gene' & min_state_cells==10,.(DonorID,retained_0,retained_1,n_states,n0,n1)]);mass[,eligible:=n0>=20 & n1>=20 & retained_0>=.8 & retained_1>=.8]
mm<-melt(mass,id.vars=c('DonorID','n_states','n0','n1','eligible'),measure.vars=c('retained_0','retained_1'),variable.name='condition',value.name='fraction');mm[,condition:=factor(condition,levels=c('retained_0','retained_1'),labels=c('UC culture','UC + blockade'))]
p3b<-ggplot(mm,aes(DonorID,fraction,fill=condition))+geom_col(position='dodge',width=.7)+geom_hline(yintercept=.8,linetype=2,color='#ADB5BE')+scale_y_continuous(labels=scales::percent,limits=c(0,1.05))+scale_fill_manual(values=c('#7D95A7','#2A8B87'))+labs(title='Fraction retained on common state support',subtitle='At least 10 cells/state/arm; at least 80% retained in each arm',x=NULL,y='Fraction of canonical neutrophils',fill=NULL)+theme_pub+theme(axis.text.x=element_text(angle=20,hjust=1),legend.text=element_text(size=8))
dd3<-dec[version=='full_gene' & min_state_cells==10 & n0>=20 & n1>=20 & retained_0>=.8 & retained_1>=.8 & program%in%c('OSM_inflammation','Degranulation','CXCR4_aging_retention')]
dd3<-melt(dd3,id.vars=c('DonorID','program'),measure.vars=c('total','composition','activity'),variable.name='component',value.name='change');dd3[,program_label:=unname(program_names[program])]
p3c<-ggplot(dd3,aes(component,change,group=DonorID,color=DonorID))+geom_hline(yintercept=0,linetype=2,color='#ADB5BE')+geom_line(alpha=.7,linewidth=.5)+geom_point(size=2)+facet_wrap(~program_label,ncol=1,scales='free_y')+guides(color='none')+labs(title='Individual donor contributions',x=NULL,y='Score change')+theme_pub+theme(axis.text.x=element_text(size=8),strip.text=element_text(size=8))
fig3<-headline(p3a|(p3b/p3c),'Figure 3 | Separating state composition from within-state activity','The decomposition is descriptive and additive; it does not identify causal mediation.','Total change = composition contribution + within-state activity contribution, exactly on the displayed score scale.\nInference requires >=20 canonical cells/arm and >=80% common-state coverage; failed support is not imputed.\nNo within-state activity contrast passes BH q < 0.05 across the 14 programs in this primary decomposition.')+plot_layout(widths=c(1.25,1),heights=c(1,1.7))
save_plot(fig3,'Figure_3_composition_activity_decomposition',11.5,10)

# Figure 4: anatomy-aware spatial association and conditional spatial null.
sp<-rd('spatial_UC_pooled_effects')[model%in%c('Unadjusted','Density + anatomy adjusted')];sp[,marker:=factor(marker,levels=rev(c('CXCR4','OSM','CD16','CD11b')))];sp[,model:=factor(model,levels=c('Unadjusted','Density + anatomy adjusted'))]
p4a<-ggplot(sp,aes(effect,marker,color=model))+geom_vline(xintercept=0,linetype=2,color='#A6B0BA')+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.15,position=pd)+geom_point(position=pd,size=2.6)+scale_color_manual(values=c('#A7B3BE','#257B98'))+labs(title='Spatial association before and after adjustment',subtitle='17 UC region IDs contribute equally; 95% intervals across IDs',x='Standardized proximity coefficient',y=NULL,color=NULL)+theme_pub
ri<-rd('spatial_ROI_effects')[Diagnosis2!='Control' & model=='Density + anatomy adjusted'];ri[,group:=factor(Diagnosis2,levels=c('UC_Noninflamed','UC_Inflamed'),labels=c('Noninflamed','Inflamed'))]
p4b<-ggplot(ri,aes(group,effect,color=group))+geom_hline(yintercept=0,linetype=2,color='#A6B0BA')+geom_point(position=position_jitter(width=.10,seed=92),size=2.1)+facet_wrap(~marker,nrow=1)+scale_color_manual(values=c('#5594A9','#C86753'),guide='none')+labs(title='Adjusted effects across individual regions',subtitle='Eight noninflamed and nine inflamed region IDs',x=NULL,y='Proximity coefficient')+theme_pub+theme(axis.text.x=element_text(angle=30,hjust=1,size=8))
nl<-rd('spatial_pooled_null_distribution');nt<-rd('spatial_restricted_label_tests');nt[,label:=paste0('Observed = ',sprintf('%.3f',observed),'\nRestricted-label q = ',fmtq(q_restricted))]
p4c<-ggplot(nl,aes(effect))+geom_histogram(bins=28,fill='#AFC8D8',color='white',linewidth=.2)+geom_vline(data=nt,aes(xintercept=observed),color='#BF5749',linewidth=.9)+geom_text(data=nt,aes(x=-Inf,y=Inf,label=label),inherit.aes=FALSE,hjust=-.05,vjust=1.1,size=2.6)+facet_wrap(~marker,nrow=1,scales='free')+labs(title='Restricted fibroblast-label permutation',subtitle='499 shuffles preserve target counts within 200-um tiles and nearest epithelial/vascular context',x='Mean adjusted coefficient under spatial null',y='Permutations')+theme_pub+theme(strip.text=element_text(size=9),axis.text=element_text(size=8))
fig4<-headline(p4a/p4b/p4c,'Figure 4 | Neutrophil phenotype and local fibroblast context','Target context: FAP-high / \u03b15\u03b21-low fibroblasts, defined by pooled-UC 75th-percentile thresholds.','Adjustment includes local fibroblast, neutrophil and other-cell counts, plus distances to epithelial, endothelial and any fibroblast cells.\nPositive coefficients indicate higher marker intensity closer to the target fibroblasts. Distinct region IDs are not assumed to be paired.\nNearest-compartment categories are anatomical proxies from existing cell labels; no new histological annotation was collected.')+plot_layout(ncol=1,heights=c(1,1,1))
save_plot(fig4,'Figure_4_spatial_context',11.5,10)

# Figure 5: all selected stromal features and statistical-method sensitivity.
pat<-rd('clinical_paired_patient_values');cr<-rd('clinical_change_comparisons')
pa<-pat[feature=='activated FAP fibroblast fraction'];pal<-melt(pa,id.vars=c('Patient','Remission_status'),measure.vars=c('pre','post'),variable.name='time',value.name='fraction');pal[,time:=factor(time,levels=c('pre','post'),labels=c('Before treatment','After treatment'))];pal[,outcome:=factor(Remission_status,levels=c('Remission','Non_Remission'),labels=c('Remission (n=6)','Nonremission (n=13)'))]
p5a<-ggplot(pal,aes(time,100*fraction,group=Patient,color=outcome))+geom_line(alpha=.65,linewidth=.7)+geom_point(size=2)+facet_wrap(~outcome)+scale_color_manual(values=c('#258D83','#C77844'),guide='none')+labs(title='Activated-FAP stromal fraction',subtitle='Paired sites averaged within each patient',x=NULL,y='Activated FAP cells / stromal cells (%)')+theme_pub+theme(axis.text.x=element_text(angle=15,hjust=1,size=8))
sds<-pat[,.(baseline_sd=sd(pre)),by=feature];cr<-merge(cr,sds,by='feature');cr[,`:=`(std_effect=effect/baseline_sd,std_low=low/baseline_sd,std_high=high/baseline_sd)]
featnames<-c('activated FAP fibroblast fraction'='Activated FAP fraction','FAP inflammatory'='FAP inflammatory program','alpha5beta1 adhesion'='\u03b15\u03b21 adhesion program','neutrophil recruitment'='Neutrophil recruitment program','OSM response'='OSM response program')
cr[,feature_label:=factor(unname(featnames[feature]),levels=rev(unname(featnames)))];cr[,model:=factor(model,levels=c('Change difference','Baseline-adjusted change'))]
p5b<-ggplot(cr,aes(std_effect,feature_label,color=model))+geom_vline(xintercept=0,linetype=2,color='#A6B0BA')+geom_errorbar(aes(xmin=std_low,xmax=std_high),orientation='y',width=.12,position=pd)+geom_point(position=pd,size=2.4)+scale_color_manual(values=c('#526F85','#298E84'))+labs(title='Remission-associated differences in change',subtitle='Effects scaled by the feature\u2019s pretreatment patient SD',x='Remission minus nonremission change (baseline SD units)',y=NULL,color=NULL)+theme_pub+theme(axis.text.y=element_text(size=8),legend.text=element_text(size=8))
clo<-rd('clinical_leave_one_patient_out')[feature=='activated FAP fibroblast fraction'];full<-cr[feature=='activated FAP fibroblast fraction' & model=='Change difference',effect]
p5c<-ggplot(clo,aes(reorder(omitted_patient,effect),100*effect))+geom_hline(yintercept=100*full,color='#258D83')+geom_hline(yintercept=0,linetype=2,color='#A6B0BA')+geom_point(size=2.2,color='#526F85')+coord_flip()+labs(title='Activated-FAP leave-one-patient-out check',subtitle='Each point omits one patient; line = full-sample estimate',x='Omitted patient',y='Difference in change (percentage points)')+theme_pub+theme(axis.text.y=element_text(size=7))
qs<-rbindlist(list(cr[model=='Change difference',.(feature,method='Welch\nBH q',qvalue=q)],cr[model=='Change difference',.(feature,method='Permutation\nBH q',qvalue=q_exact)],cr[model=='Baseline-adjusted change',.(feature,method='Baseline-adjusted\nHC3 BH q',qvalue=q)]))
qs[,feature_label:=factor(unname(featnames[feature]),levels=rev(unname(featnames)))];qs[,method:=factor(method,levels=c('Welch\nBH q','Permutation\nBH q','Baseline-adjusted\nHC3 BH q'))]
p5d<-ggplot(qs,aes(method,feature_label))+geom_tile(fill='#F0F4F7',color='white',linewidth=2)+geom_text(aes(label=fmtq(qvalue)),size=3.4)+labs(title='Statistical-method sensitivity',subtitle='Five stromal endpoints; all results retained',x=NULL,y=NULL)+theme_pub+theme(axis.text.y=element_text(size=8),axis.line=element_blank(),axis.ticks=element_blank(),axis.text.x=element_text(size=8))
fig5<-headline((p5a|p5b)/(p5c|p5d),'Figure 5 | Treatment-associated stromal change in TAURUS','Activated-FAP fraction: 6 remission / 13 nonremission patients. Program scores: 5 / 11.','All effects are exploratory outcome associations, not predictive performance or evidence of a neutrophil mechanism.\nTAURUS did not capture neutrophils. Welch tests are the primary mean-difference analysis; permutation tests assume exchangeable labels.\nBaseline-adjusted intervals use HC3 heteroscedasticity-robust uncertainty. All intervals are pointwise 95% intervals.')+plot_layout(heights=c(1,1.2))
save_plot(fig5,'Figure_5_longitudinal_stromal_context',12,10)

# Figure 6: continuous measurements avoid adopting provisional positivity thresholds.
fm<-rd('flow_continuous_figure_values');ff<-rd('flow_continuous_effects')
gr<-c('N','N+NF','N+IF','N+ATN','N+IF+ATN');gl<-c('Alone','Noninflamed\nfibroblasts','Inflamed\nfibroblasts','Alone\n+ ATN-161','Inflamed\n+ ATN-161')
fm<-fm[group%in%gr];fm[,condition:=factor(group,levels=gr,labels=gl)]
summary<-fm[,.(mean=mean(median_fi),lo=mean(median_fi)-qt(.975,.N-1)*sd(median_fi)/sqrt(.N),hi=mean(median_fi)+qt(.975,.N-1)*sd(median_fi)/sqrt(.N)),by=.(marker,condition)]
p6a<-ggplot(fm,aes(condition,median_fi,color=condition))+geom_point(position=position_jitter(width=.12,seed=15),size=2.4,alpha=.85)+geom_errorbar(data=summary,aes(y=mean,ymin=lo,ymax=hi),width=.15,inherit.aes=TRUE,color='#2E3F4D')+geom_point(data=summary,aes(y=mean),shape=18,size=3.5,color='#2E3F4D')+facet_wrap(~marker,scales='free_y',nrow=1)+scale_color_manual(values=c('#8B97A3','#579EB1','#C57849','#849AAF','#298E85'),guide='none')+labs(title='Continuous fluorescence in recorded biological samples',subtitle='Points = sample medians; diamonds and bars = group mean and 95% t interval',x=NULL,y='Median compensated fluorescence (a.u.)')+theme_pub+theme(axis.text.x=element_text(size=8))
ct<-ff[contrast%in%c('ATN_in_UC','ATN_alone')];ct[,context:=factor(contrast,levels=c('ATN_alone','ATN_in_UC'),labels=c('Neutrophils alone','With inflamed fibroblasts'))]
p6b<-ggplot(ct,aes(effect,context,color=context))+geom_vline(xintercept=0,linetype=2,color='#A6B0BA')+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.15)+geom_point(size=2.8)+facet_wrap(~marker,scales='free_x')+scale_color_manual(values=c('#8199AC','#258D83'),guide='none')+labs(title='ATN-161 effects differ by culture context',subtitle='Unpaired mean differences; Welch intervals',x='Treatment minus untreated fluorescence (a.u.)',y=NULL)+theme_pub+theme(axis.text.y=element_text(size=8))
it<-ff[contrast=='ATN_context_interaction']
p6c<-ggplot(it,aes(effect,'Interaction'))+geom_vline(xintercept=0,linetype=2,color='#A6B0BA')+geom_errorbar(aes(xmin=low,xmax=high),orientation='y',width=.15,color='#B85D4D')+geom_point(size=3,color='#B85D4D')+facet_wrap(~marker,scales='free_x')+labs(title='Exploratory four-group context interaction',subtitle='Six independent samples/arm; donor pairing is unconfirmed',x='[ATN effect with fibroblasts] - [ATN effect alone] (a.u.)',y=NULL)+theme_pub+theme(axis.text.y=element_text(size=8))
fig6<-headline(p6a/p6b/p6c,'Figure 6 | Continuous flow readouts: exploratory support','Reanalysis of existing corrected review measurements; no positivity gates were adopted.','CXCR4 and OSM detector identities are retained from the existing audit. B515/B710 are excluded because marker identities conflict.\nCo-culture lacks matched marker FMOs and a uniform viability channel; parent gates and compensation retain the audit\u2019s limitations.\nThe original 36-contrast intensity family had no Holm-adjusted p < 0.05. New interaction intervals are exploratory and unadjusted.')+plot_layout(heights=c(1.5,1,1))
save_plot(fig6,'Figure_6_exploratory_flow_context',11.5,10.5)

# Figure 7: full-gene pseudobulk corroboration with estimated residual gene correlation.
pb<-rd('pseudobulk_program_correlation_sensitivity')[correlation_method=='Estimated within gene set']
pb[,program_label:=plab(program)];pb[,comparison:=factor(paste(contrast,population,sep=' | '),levels=c('alpha_interaction | Resolved','alpha_interaction | All_annotated','alpha_in_UC | Resolved','alpha_in_UC | All_annotated'),labels=c('Interaction\nresolved','Interaction\nall annotated','UC blockade\nresolved','UC blockade\nall annotated'))]
pb[,signed_q:=ifelse(Direction=='Up',1,-1)*pmin(4,-log10(pmax(FDR,1e-12)))]
p7a<-ggplot(pb,aes(comparison,program_label,fill=signed_q))+geom_tile(color='white',linewidth=.5)+geom_text(aes(label=fmtq(FDR)),size=2.6)+scale_fill_gradient2(low='#35779B',mid='white',high='#CB6E5F',midpoint=0,limits=c(-4,4))+labs(title='Competitive tests with estimated gene correlation',subtitle='Tile text = BH q across 14 programs per comparison',x=NULL,y=NULL,fill='Signed\n-log10 q')+theme_pub+theme(axis.text.y=element_text(size=8),axis.text.x=element_text(size=7.5),legend.position='bottom')
de7<-rd('full_gene_pseudobulk_differential_expression')
gs7<-c('OSM','IL1B','TNF','NFKBIA','CXCL8','CCL3','CCL4','IL1R2','SOCS3','CXCR4','LTF','BPI')
de7<-de7[population=='Resolved' & gene%in%gs7 & contrast%in%c('alpha_interaction','alpha_in_UC','UC_vs_control_fibroblasts')]
de7[,gene_label:=factor(gene,levels=rev(gs7))];de7[,ct:=factor(contrast,levels=c('UC_vs_control_fibroblasts','alpha_in_UC','alpha_interaction'),labels=c('UC vs control\nfibroblasts','Blockade in\nUC culture','Context\ninteraction'))]
p7b<-ggplot(de7,aes(ct,gene_label,fill=logFC))+geom_tile(color='white',linewidth=.5)+geom_text(aes(label=paste0(sprintf('%+.1f',logFC),ifelse(FDR<.05,'*',''))),size=2.8)+scale_fill_gradient2(low='#216A94',mid='white',high='#CA6B59',midpoint=0)+labs(title='Selected gene effects from full-count models',subtitle='All nine OSM-program genes plus CXCR4, LTF and BPI',x=NULL,y=NULL,fill='log2 fold\nchange')+theme_pub+theme(axis.text.x=element_text(size=8),legend.position='bottom')
fig7<-headline(p7a|p7b,'Figure 7 | Full-count pseudobulk corroboration','Models use at least 20 cells/arm and recorded donor blocking; interaction n=4, UC-blockade n=5.','A: CAMERA estimates residual gene correlation; blue = relative down-enrichment, red = up-enrichment. Color is evidence, not magnitude.\nAll annotated = lineage-retained neutrophils including unresolved cells; original contaminant exclusions are preserved.\nB: edgeR quasi-likelihood gene effects. * BH FDR < 0.05 among all tested genes in that comparison; blank tiles indicate untested genes.\nPseudobulk totals and per-cell mean scores measure different aspects of a population and need not have identical significance.')+plot_layout(widths=c(1.25,1))
save_plot(fig7,'Figure_7_pseudobulk_corroboration',12,9)
tmp_pdf<-file.path(ROOT,'tmp/pdfs/reframed_analysis_figures');dir.create(tmp_pdf,recursive=TRUE,showWarnings=FALSE)
for(f in sort(list.files(file.path(OUT,'objects'),pattern='^Figure_[1-7].*_plot\\.rds$',full.names=TRUE))){
 ob<-readRDS(f);name<-sub('_plot\\.rds$','.pdf',basename(f));ggsave(file.path(tmp_pdf,name),ob$plot,width=ob$width,height=ob$height,device=cairo_pdf,bg='white',limitsize=FALSE)
}
message('Seven figures exported as PNG, editable SVG and intermediate vector PDF pages')
